### ISSUE TITLE
Error object inconsistency

### ISSUE THREAD

**Issue by lockie** [hfaran/Tornado-JSON#76]
Hi!
For invalid JSON inputs/outputs resulting JSON reply is `{ "status": "failure", "data": "error message blah"  }`, as well as it is for `api_assert` calls. Nonetheless, for unhandled exceptions producing 500 internal server error it looks like `{ "status": "failure", "message": "Internal server error"  }`, which makes it a bit diffucult to handle on client side. Could it be a bit more consistent pwease?

**Comment by hfaran** [comment]
Hi @lockie,

Tornado-JSON is in fact designed to behave exactly this way and I will expound on why:
There are only two exception classes which return their log messages in failure responses; they are `APIError` (which `api_assert` raises), and `ValidationError` (which is raised when input/output validation fails on requests/responses). 

The reason this is this way is because these two exceptions have messages that are designed to be read by clients. An unhandled exception does not, and has the potential to leak internal data which you may not want the client to see.

Based on Tornado-JSON's philosophy at least, a good API should only ever raise `APIError` as a way of signalling to the client (with the appropriate HTTP Error Code); other unhandled exceptions are considered bugs in the server code and should be resolved or replaced with appropriate `APIError` assertions. The client should never be debugging the server :)

Now, if you're developing and in fact want to see all of these messages, you can [enable the *debug* setting](http://serverfault.com/questions/274014/how-to-set-debug-mode-in-tornado) which will allow you to see messages from unhandled exceptions as the `data` property in the response (which might look something like: `{"status": "failure, "message": "Internal Server Error", "data": "TypeError: blah blah blah", "code": 500}`). Of course, you don't want to enable this in a production API.

[Tornado-JSON's `write_error` method which handles this is defined here if you want to give it a quick look; the comment essentially states the same thing as I've said here.](https://github.com/hfaran/Tornado-JSON/blob/master/tornado_json/requesthandlers.py#L50)

**Comment by hfaran** [comment]
I'm going to close the issue but if you have more comments/want to continue the discussion, feel free to! As you can probably see, I love talking. :)
(Also, any suggestions for improvement would be welcome.)

**Comment by lockie** [comment]
Thank you for thorough explanation @hfaran !

> An unhandled exception does not, and has the potential to leak internal data which you may not want the client to see.

Thats a good point, I was missing it.

But actually I've meant simpler thing: on client-side, if you want to show some meaningful message to a user, you'll have to check both `message` and `data` fields (since latter could be missing; unhandled exceptions on server side do happen sometimes :scream:). This checking is especially awkward when you're using language with static typing, like I do.
Swapping `message` and `data` in case of unhandled exception would make it lot easier. Moreover, `message` field does not conform with [JSON API](http://jsonapi.org/format) anyways, so I suggest doing it. I could provide you with corresponding pull-request if you want.

**Comment by hfaran** [comment]
Tornado-JSON actually doesn't adhere to JSON API; my reason for doing this was because I wanted to Tornado-JSON to be simple and not bogged down by the significant complexity of a spec like JSON API, which, let's admit is gigantic.

Currently, Tornado-JSON follows [JSend](http://labs.omniti.com/labs/jsend) (as is said in the README) because the spec is simple and straightforward and let's you just get on with building small APIs. I am not opposed to following JSON API in the future, but some significant work would have to go into it before that happens.

-----

Regarding swapping `message` and `data`: hmm, I'm afraid I don't **quite** understand what you mean. If you could elaborate more or provide some code snippets for context, that would be great.

**Comment by lockie** [comment]
> JSON API, which, let's admit is gigantic.

I've read it all while designing API for my project, and, well, it is observable :)

> Currently, Tornado-JSON follows JSend 

Oh, I see. At first glance I've confused it with some kind of library.

> hmm, I'm afraid I don't quite understand what you mean
I've done a PR.

**Comment by lockie** [comment]
Okay, we've finally pinpointed the issue. As you've cited in #77, `message` should contain meaningful, end-user-readable (or at the least log-worthy) message, explaining what went wrong, but for, erm, handled exceptions (that being `api_assert` and invalid data submitted) it ends up in `data` field [here](https://github.com/hfaran/Tornado-JSON/blob/master/tornado_json/jsend.py#L32). Is there particular reason for this behaviour?

**Comment by hfaran** [comment]
See the JSend spec for the answer to that ;)

I suppose it would be better for the exceptions to be structured, but if you consider this all, I would still think that having error data in well, `data`, makes more sense and that the changes in #77 aren't so necessary; if you enabled `debug` mode, you only need to check the `data` the key for all responses rather than check `message`.

**Comment by lockie** [comment]
Oh, now I see.

> There is no message key in success or fail responses.

Thats a strange specification, but, well, that's a specification :)
Thank you.
